spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    url: jdbc:mysql://containers-us-west-26.railway.app:6498/railway
    password: msDZgSqlCWTMmFzfPTsp
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: 'true'
      properties:
        hibernate:
          format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: tarikibrahimovic2016@gmail.com
    password: bbewzvegsfmlcdhf
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  cloudinary:
    CLOUDINARY_URL: cloudinary://619781217835657:zSGen1-d99dsWYZ-x01JSOrxm2g@du9hzqeoa
