spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/crypto
    password: Tarik2508
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: 'true'
      properties:
        hibernate:
          format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: tarikibrahimovic2016@gmail.com
    password: kmhikbyzxwtcvoxk

  cloudinary:
    CLOUDINARY_URL: cloudinary://619781217835657:zSGen1-d99dsWYZ-x01JSOrxm2g@du9hzqeoa

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

